/*
 * FINGER_PRINT_PRIV.h
 *
 *  Created on: Mar 12, 2023
 *      Author: joseph
 */

#ifndef FINGER_PRINT_FINGER_PRINT_PRIV_H_
#define FINGER_PRINT_FINGER_PRINT_PRIV_H_

#define FP_HEADER_UPPER_BYTE				0xEF
#define FP_HEADER_LOWER_BYTE				0x01

#define FP_ADDRESS_BYTE						0xFF

#define FP_IDENTIFIER_COMMAND				0x01


#define FP_HANDSHAKE_COMMAND				0x40
#define FP_CHECKSENSOR_COMMAND				0x36
#define FP_COLLECT_FINGER_IMAGE_COMMAND		0x01
#define FP_GENERATE_CHARACTER_FILE_COMMAND	0x02
#define FP_GENERATE_TEMPLATE_COMMAND		0x05
#define FP_STORE_TEMPLATE_COMMAND			0x06
#define FP_MATCHING_TWO_FINGER_COMMAND		0x03
#define FP_SEARCH_FINGER_LIBRARY_COMMAND	0x04

#endif /* FINGER_PRINT_FINGER_PRINT_PRIV_H_ */
